### ISSUE TITLE
hard negative index npy file

### ISSUE THREAD

**Issue by kyu1chi** [youganglyu/DCT#2]
Hi，
I have a question about how to generate the hard negative index npy file？
Thanks.

**Comment by youganglyu** [comment]
Hello,

To use MNLI as an example, please follow these steps:

After each epoch of fine-tuning with tiny-bert, generate a representation for all examples. The output will be saved in the file named mnli_tbert_emb_epoch xx.
Subsequently, execute the provided code to filter out negative samples.

step1	split_012_fever
step2	find_bias_data_hard_fever
step3	search_neg_all_fever
step4	neg_all_fever
step5	final_neg_index_fever
